import type { Comparable, ReferenceValue } from "./types";

export const mockReferences: ReferenceValue[] = [
  {
    id: "ref-palermo-venta-depto",
    zone: "Palermo",
    operation: "VENTA",
    propertyType: "DEPTO",
    currency: "USD",
    pricePerM2: 2400,
    valuePerM2: 2400, // compat
    p25: 2100,
    p75: 2800,
    updatedAt: new Date().toISOString(),
    source: { kind: "Portal", note: "Promedio portales + depuración manual" },
    status: "VALIDADO",
  },
  {
    id: "ref-caballito-venta-depto",
    zone: "Caballito",
    operation: "VENTA",
    propertyType: "DEPTO",
    currency: "USD",
    pricePerM2: 1900,
    valuePerM2: 1900, // compat
    p25: 1700,
    p75: 2200,
    updatedAt: new Date().toISOString(),
    source: { kind: "Tasación", note: "Criterio interno (demo)" },
    status: "PENDIENTE",
  },
  {
    id: "ref-belgrano-alquiler-depto",
    zone: "Belgrano",
    operation: "ALQUILER",
    propertyType: "DEPTO",
    currency: "ARS",
    pricePerM2: 8500,
    valuePerM2: 8500, // compat
    p25: 7000,
    p75: 10500,
    updatedAt: new Date().toISOString(),
    source: { kind: "Manual", note: "Carga manual (demo)" },
    status: "PENDIENTE",
  },
];

export const mockComparables: Comparable[] = [
  {
    id: "cmp1",
    zone: "Palermo",
    operation: "VENTA",
    propertyType: "DEPTO",
    price: 165000,
    currency: "USD",
    areaM2: 70,
    rooms: 3,
    ageYears: 12,
    condition: "MUY_BUENO",
    hasGarage: false,
    hasBalcony: true,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 9).toISOString(),
    // lat: -34.5794,
    // lng: -58.4259,
  },
  {
    id: "cmp2",
    zone: "Palermo",
    operation: "VENTA",
    propertyType: "DEPTO",
    price: 210000,
    currency: "USD",
    areaM2: 85,
    rooms: 4,
    ageYears: 5,
    condition: "A_ESTRENAR",
    hasGarage: true,
    hasBalcony: true,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 20).toISOString(),
    // lat: -34.5884,
    // lng: -58.3925,
  },
  {
    id: "cmp3",
    zone: "Caballito",
    operation: "VENTA",
    propertyType: "DEPTO",
    price: 98000,
    currency: "USD",
    areaM2: 55,
    rooms: 2,
    ageYears: 18,
    condition: "BUENO",
    hasGarage: false,
    hasBalcony: true,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    // lat: -34.6186,
    // lng: -58.442,
  },
];
